name: Test Application

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and start containers
      run: |
        docker compose build
        docker compose up -d
        
    - name: Wait for services to be ready
      run: |
        # Wait for PostgreSQL to be ready
        timeout 30s bash -c 'until docker compose exec db pg_isready; do sleep 1; done'
        
    - name: Load test data
      env:
        GITHUB_ACTIONS: 'true'
      run: |
        # Wait a bit for the web service to be ready
        sleep 10
        # Load test data with small dataset for testing
        docker compose exec db python3 /docker-entrypoint-initdb.d/load_test_data.py
        
    - name: Check for errors
      run: |
        # Check if containers are running
        docker compose ps
        # Check container logs for errors
        docker compose logs
        
    - name: Cleanup
      if: always()
      run: |
        docker compose down -v 